
name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-latest
          triplet: "x64-linux"
          compiler: g++-9
        - os: windows-latest
          triplet: "x64-windows"

    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install (gcc-9) (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "CXX=${{ matrix.config.compiler }}" >> $GITHUB_ENV
    - name: vcpkg
      shell: bash
      run: |
        pwd
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg install cxxopts:${{ matrix.config.triplet }} fmt:${{ matrix.config.triplet }} spdlog:${{ matrix.config.triplet }}
    - name: check vcpkg
      run: |
        cd vcpkg
        ./vcpkg list
    - name: cmake
      run: cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=${{ matrix.config.triplet }} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=Artifact
    - name: build
      run: cmake --build . --config Release
    - name: run dart
      run: ./Artifact/bg-generation-penrose Artifact/dart_11.svg 11
    - name: run dart with step
      run: ./Artifact/bg-generation-penrose Artifact/dart_11_7.svg --step 7 --level 11 --threshold 6
    - name: run dart neon
      run: ./Artifact/bg-generation-penrose Artifact/dart_6_2_neon.svg --step 2 --level 6 --threshold 6 --neon
    - name: run rhombus
      run: ./Artifact/bg-generation-penrose --rhombus Artifact/rhombus_11_7.svg 11 7
    - uses: actions/upload-artifact@v1
      with:
        name: bg-generation-penrose-${{ matrix.config.triplet }}
        path: Artifact
